# Generated by Django 3.0.6 on 2020-05-18 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image',
        ),
    ]
